# Generated by Django 5.2.14 on 2026-05-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва організації')),
                ('description', models.TextField(verbose_name='Опис')),
                ('volunteers_count', models.PositiveIntegerField(verbose_name='Кількість волонтерів')),
            ],
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва збору')),
                ('description', models.TextField(verbose_name='Опис збору')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потрібна сума')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зібрана сума')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaigns', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва проєкту')),
                ('description', models.TextField(verbose_name='Опис проєкту')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва ресурсу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='organizations.organization', verbose_name='Організація')),
            ],
        ),
    ]
